# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nelson/Documents/ex6/transform_Bright

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nelson/Documents/ex6/transform_Bright/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nelson/Documents/ex6/transform_Bright/build/CMakeFiles /home/nelson/Documents/ex6/transform_Bright/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nelson/Documents/ex6/transform_Bright/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bright

# Build rule for target.
bright: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bright
.PHONY : bright

# fast build rule for target.
bright/fast:
	$(MAKE) -f CMakeFiles/bright.dir/build.make CMakeFiles/bright.dir/build
.PHONY : bright/fast

transform_Bright.o: transform_Bright.cpp.o

.PHONY : transform_Bright.o

# target to build an object file
transform_Bright.cpp.o:
	$(MAKE) -f CMakeFiles/bright.dir/build.make CMakeFiles/bright.dir/transform_Bright.cpp.o
.PHONY : transform_Bright.cpp.o

transform_Bright.i: transform_Bright.cpp.i

.PHONY : transform_Bright.i

# target to preprocess a source file
transform_Bright.cpp.i:
	$(MAKE) -f CMakeFiles/bright.dir/build.make CMakeFiles/bright.dir/transform_Bright.cpp.i
.PHONY : transform_Bright.cpp.i

transform_Bright.s: transform_Bright.cpp.s

.PHONY : transform_Bright.s

# target to generate assembly for a file
transform_Bright.cpp.s:
	$(MAKE) -f CMakeFiles/bright.dir/build.make CMakeFiles/bright.dir/transform_Bright.cpp.s
.PHONY : transform_Bright.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bright"
	@echo "... edit_cache"
	@echo "... transform_Bright.o"
	@echo "... transform_Bright.i"
	@echo "... transform_Bright.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

